import 'hotel_model.dart'; // Add this package

class HotelService {
  static List<Hotel> getAllHotels() {
    return [
      Hotel(
        id: '1',
        name: 'Canaves Oia',
        description: 'Luxury hotel in Santorini',
        location: 'Santorini, Greece',
        lat: 37.0950,
        lng: 25.3731,
        imagePath: 'assets/hotels/canaves.jpg',
        rating: 4.8,
        price: 450,
      ),
      Hotel(
        id: '2',
        name: 'Badrutts Palace',
        description: 'Iconic Swiss hotel',
        location: 'St. Moritz, Switzerland',
        lat: 46.4883,
        lng: 9.8353,
        imagePath: 'assets/hotels/badrutts.jpg',
        rating: 4.9,
        price: 600,
      ),
      Hotel(
        id: '3',
        name: 'Le Bristol Paris',
        description: '5-star hotel in Paris',
        location: 'Paris, France',
        lat: 48.8699,
        lng: 2.3138,
        imagePath: 'assets/hotels/le_bristol.jpg',
        rating: 4.7,
        price: 550,
      ),
      Hotel(
        id: '4',
        name: 'Ayana Resort',
        description: 'Luxury resort in Bali',
        location: 'Bali, Indonesia',
        lat: -8.8241,
        lng: 115.1678,
        imagePath: 'assets/hotels/ayana.jpg',
        rating: 4.8,
        price: 350,
      ),
      Hotel(
        id: '5',
        name: 'Mandarin Oriental',
        description: 'Luxury hotel in Paris',
        location: 'Paris, France',
        lat: 48.8650,
        lng: 2.3217,
        imagePath: 'assets/hotels/mandarin.jpg',
        rating: 4.8,
        price: 500,
      ),
      Hotel(
        id: '6',
        name: 'Four Seasons',
        description: 'Florence luxury hotel',
        location: 'Florence, Italy',
        lat: 43.5438,
        lng: 10.3062,
        imagePath: 'assets/hotels/four_seasons.jpg',
        rating: 4.6,
        price: 480,
      ),
      Hotel(
        id: '7',
        name: 'Burj Al Arab',
        description: 'Iconic Dubai hotel',
        location: 'Dubai, UAE',
        lat: 25.1412,
        lng: 55.1852,
        imagePath: 'assets/hotels/burj_al_arab.jpg',
        rating: 4.9,
        price: 800,
      ),
      Hotel(
        id: '8',
        name: 'Soneva Fushi',
        description: 'Maldives luxury resort',
        location: 'Maldives',
        lat: 5.1117,
        lng: 73.0264,
        imagePath: 'assets/hotels/soneva_fushi.jpg',
        rating: 4.7,
        price: 650,
      ),
      Hotel(
        id: '9',
        name: 'Hotel Sharda',
        description: 'Hotel in Pakistan',
        location: 'Pakistan',
        lat: 34.7669,
        lng: 76.1292,
        imagePath: 'assets/hotels/hotel_sharda.jpg',
        rating: 3.8,
        price: 50,
      ),
      Hotel(
        id: '10',
        name: 'Movenpick',
        description: 'Zurich hotel',
        location: 'Zurich, Switzerland',
        lat: 47.0502,
        lng: 8.3093,
        imagePath: 'assets/hotels/movenpick.jpg',
        rating: 4.3,
        price: 180,
      ),
      Hotel(
        id: '11',
        name: 'PTDC Hotel',
        description: 'Government hotel in Pakistan',
        location: 'Pakistan',
        lat: 33.8597,
        lng: 73.1268,
        imagePath: 'assets/hotels/ptdc.jpg',
        rating: 3.5,
        price: 40,
      ),
      Hotel(
        id: '12',
        name: 'PC Bhurban',
        description: 'Pearl Continental Bhurban',
        location: 'Bhurban, Pakistan',
        lat: 33.9132,
        lng: 73.3779,
        imagePath: 'assets/hotels/pc_bhurban.jpg',
        rating: 4.2,
        price: 120,
      ),
      Hotel(
        id: '13',
        name: 'PC Lahore',
        description: 'Pearl Continental Lahore',
        location: 'Lahore, Pakistan',
        lat: 31.5546,
        lng: 74.3572,
        imagePath: 'assets/hotels/pc_lahore.jpg',
        rating: 4.3,
        price: 130,
      ),
      Hotel(
        id: '14',
        name: 'Khan Hotel',
        description: 'Hotel in Northern Pakistan',
        location: 'Gilgit-Baltistan, Pakistan',
        lat: 35.2948,
        lng: 74.1790,
        imagePath: 'assets/hotels/khan_hotel.jpg',
        rating: 3.6,
        price: 35,
      ),
      Hotel(
        id: '15',
        name: 'Raikot Sarai',
        description: 'Hotel near Nanga Parbat',
        location: 'Raikot, Pakistan',
        lat: 35.9167,
        lng: 74.3000,
        imagePath: 'assets/hotels/raikot_sarai.jpg',
        rating: 3.8,
        price: 45,
      ),
      Hotel(
        id: '16',
        name: 'Serena Swat',
        description: 'Luxury hotel in Swat',
        location: 'Swat, Pakistan',
        lat: 35.2131,
        lng: 72.4231,
        imagePath: 'assets/hotels/serena_swat.jpg',
        rating: 4.5,
        price: 150,
      ),
      Hotel(
        id: '17',
        name: 'Shangrila Resort',
        description: 'Resort in Skardu',
        location: 'Skardu, Pakistan',
        lat: 35.3438,
        lng: 75.5439,
        imagePath: 'assets/hotels/shangrila_resort.jpg',
        rating: 4.4,
        price: 140,
      ),
      Hotel(
        id: '18',
        name: 'Serena Hunza',
        description: 'Luxury hotel in Hunza Valley',
        location: 'Hunza, Pakistan',
        lat: 36.3214,
        lng: 74.6717,
        imagePath: 'assets/hotels/serena_hunza.jpg',
        rating: 4.6,
        price: 160,
      ),
    ];
  }

  static Hotel? findHotelByName(String name) {
    return getAllHotels().firstWhere(
          (hotel) => hotel.name.toLowerCase().contains(name.toLowerCase()),
      orElse: () => throw Exception('Hotel not found'),
    );
  }

  static List<Hotel> getHotelsByCountry(String country) {
    return getAllHotels().where((hotel) => hotel.location.contains(country)).toList();
  }
}