// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjHubOL4r7RkDeL6Qee7QSWF4jCTNDGbg',
    appId: '1:752416442170:web:1494093b95ed3f70d83203',
    messagingSenderId: '752416442170',
    projectId: 'travelmate-100',
    authDomain: 'travelmate-100.firebaseapp.com',
    storageBucket: 'travelmate-100.firebasestorage.app',
    measurementId: 'G-ZD6VP9V25G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlXnFWSjYFvYtueULRYcRdjkNeU7fDJEE',
    appId: '1:752416442170:android:6acbbe79713a129fd83203',
    messagingSenderId: '752416442170',
    projectId: 'travelmate-100',
    storageBucket: 'travelmate-100.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf3D74EbPcBd2HOUCBLb0U9bAdsJ092Eg',
    appId: '1:752416442170:ios:176910ced0566a06d83203',
    messagingSenderId: '752416442170',
    projectId: 'travelmate-100',
    storageBucket: 'travelmate-100.firebasestorage.app',
    iosBundleId: 'com.example.travelmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf3D74EbPcBd2HOUCBLb0U9bAdsJ092Eg',
    appId: '1:752416442170:ios:176910ced0566a06d83203',
    messagingSenderId: '752416442170',
    projectId: 'travelmate-100',
    storageBucket: 'travelmate-100.firebasestorage.app',
    iosBundleId: 'com.example.travelmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjHubOL4r7RkDeL6Qee7QSWF4jCTNDGbg',
    appId: '1:752416442170:web:df590566e53651f9d83203',
    messagingSenderId: '752416442170',
    projectId: 'travelmate-100',
    authDomain: 'travelmate-100.firebaseapp.com',
    storageBucket: 'travelmate-100.firebasestorage.app',
    measurementId: 'G-NL9TC7TKJ7',
  );
}
